aws_region          = "us-east-1"
environment         = "staging"
project_name        = "multi-env-infra"
vpc_cidr            = "10.1.0.0/16"
public_subnet_cidr  = "10.1.1.0/24"
private_subnet_cidr = "10.1.2.0/24"
instance_type       = "t3.small"
